--[[
  Estuary API
 
  This is the API for the Estuary application.
 
  OpenAPI spec version: 0.0.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- types_ipfs_list_pin_status_response class
local types_ipfs_list_pin_status_response = {}
local types_ipfs_list_pin_status_response_mt = {
	__name = "types_ipfs_list_pin_status_response";
	__index = types_ipfs_list_pin_status_response;
}

local function cast_types_ipfs_list_pin_status_response(t)
	return setmetatable(t, types_ipfs_list_pin_status_response_mt)
end

local function new_types_ipfs_list_pin_status_response(count, results)
	return cast_types_ipfs_list_pin_status_response({
		["count"] = count;
		["results"] = results;
	})
end

return {
	cast = cast_types_ipfs_list_pin_status_response;
	new = new_types_ipfs_list_pin_status_response;
}
