=begin
#Estuary API

#This is the API for the Estuary application.

OpenAPI spec version: 0.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.39
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::PeeringPeeringPeer
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PeeringPeeringPeer' do
  before do
    # run before each test
    @instance = SwaggerClient::PeeringPeeringPeer.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PeeringPeeringPeer' do
    it 'should create an instance of PeeringPeeringPeer' do
      expect(@instance).to be_instance_of(SwaggerClient::PeeringPeeringPeer)
    end
  end
  describe 'test attribute "addrs"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "connected"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
