# This file is auto-generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function

Describe 'estuary-client NetApi' {
    Context 'NetApi' {
        It 'Invoke-NetApiNetAddrsGet' {
            $ret = Invoke-PetApiGetPetById
            #$ret | Should BeOfType estuary-client.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'NetApi' {
        It 'Invoke-NetApiPublicMinersFailuresMinerGet' {
            $ret = Invoke-PetApiGetPetById -miner "TEST_VALUE"
            #$ret | Should BeOfType estuary-client.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'NetApi' {
        It 'Invoke-NetApiPublicMinersGet' {
            $ret = Invoke-PetApiGetPetById
            #$ret | Should BeOfType estuary-client.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'NetApi' {
        It 'Invoke-NetApiPublicNetAddrsGet' {
            $ret = Invoke-PetApiGetPetById
            #$ret | Should BeOfType estuary-client.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'NetApi' {
        It 'Invoke-NetApiPublicNetPeersGet' {
            $ret = Invoke-PetApiGetPetById
            #$ret | Should BeOfType estuary-client.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

}
