# coding: utf-8

"""
    Estuary API

    This is the API for the Estuary application.  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import estuary_client
from estuary_client.models.collections_collection import CollectionsCollection  # noqa: E501
from estuary_client.rest import ApiException


class TestCollectionsCollection(unittest.TestCase):
    """CollectionsCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollectionsCollection(self):
        """Test CollectionsCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = estuary_client.models.collections_collection.CollectionsCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
