/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GithubComApplicationResearchEstuaryApiV2ClaimMsgResponse model module.
 * @module model/GithubComApplicationResearchEstuaryApiV2ClaimMsgResponse
 * @version 1.0.6
 */
export class GithubComApplicationResearchEstuaryApiV2ClaimMsgResponse {
  /**
   * Constructs a new <code>GithubComApplicationResearchEstuaryApiV2ClaimMsgResponse</code>.
   * @alias module:model/GithubComApplicationResearchEstuaryApiV2ClaimMsgResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GithubComApplicationResearchEstuaryApiV2ClaimMsgResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GithubComApplicationResearchEstuaryApiV2ClaimMsgResponse} obj Optional instance to populate.
   * @return {module:model/GithubComApplicationResearchEstuaryApiV2ClaimMsgResponse} The populated <code>GithubComApplicationResearchEstuaryApiV2ClaimMsgResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GithubComApplicationResearchEstuaryApiV2ClaimMsgResponse();
      if (data.hasOwnProperty('hexmsg'))
        obj.hexmsg = ApiClient.convertToType(data['hexmsg'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} hexmsg
 */
GithubComApplicationResearchEstuaryApiV2ClaimMsgResponse.prototype.hexmsg = undefined;

