/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EstuaryClient) {
      root.EstuaryClient = {};
    }
    root.EstuaryClient.MainChannelIDParam = factory(root.EstuaryClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The MainChannelIDParam model module.
   * @module model/MainChannelIDParam
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>MainChannelIDParam</code>.
   * @alias module:model/MainChannelIDParam
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>MainChannelIDParam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MainChannelIDParam} obj Optional instance to populate.
   * @return {module:model/MainChannelIDParam} The populated <code>MainChannelIDParam</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('initiator'))
        obj.initiator = ApiClient.convertToType(data['initiator'], 'String');
      if (data.hasOwnProperty('responder'))
        obj.responder = ApiClient.convertToType(data['responder'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} initiator
   */
  exports.prototype.initiator = undefined;

  /**
   * @member {String} responder
   */
  exports.prototype.responder = undefined;


  return exports;

}));
