/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.40
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddressAddress} from './AddressAddress';

/**
 * The MinerMinerChainInfo model module.
 * @module model/MinerMinerChainInfo
 * @version 1.0.6
 */
export class MinerMinerChainInfo {
  /**
   * Constructs a new <code>MinerMinerChainInfo</code>.
   * @alias module:model/MinerMinerChainInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MinerMinerChainInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MinerMinerChainInfo} obj Optional instance to populate.
   * @return {module:model/MinerMinerChainInfo} The populated <code>MinerMinerChainInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MinerMinerChainInfo();
      if (data.hasOwnProperty('addresses'))
        obj.addresses = ApiClient.convertToType(data['addresses'], ['String']);
      if (data.hasOwnProperty('owner'))
        obj.owner = AddressAddress.constructFromObject(data['owner']);
      if (data.hasOwnProperty('peerId'))
        obj.peerId = ApiClient.convertToType(data['peerId'], 'String');
      if (data.hasOwnProperty('worker'))
        obj.worker = AddressAddress.constructFromObject(data['worker']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} addresses
 */
MinerMinerChainInfo.prototype.addresses = undefined;

/**
 * @member {module:model/AddressAddress} owner
 */
MinerMinerChainInfo.prototype.owner = undefined;

/**
 * @member {String} peerId
 */
MinerMinerChainInfo.prototype.peerId = undefined;

/**
 * @member {module:model/AddressAddress} worker
 */
MinerMinerChainInfo.prototype.worker = undefined;

