/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CidCid} from './CidCid';

/**
 * The UtilDbCID model module.
 * @module model/UtilDbCID
 * @version 1.0.6
 */
export class UtilDbCID {
  /**
   * Constructs a new <code>UtilDbCID</code>.
   * @alias module:model/UtilDbCID
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UtilDbCID</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UtilDbCID} obj Optional instance to populate.
   * @return {module:model/UtilDbCID} The populated <code>UtilDbCID</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UtilDbCID();
      if (data.hasOwnProperty('cid'))
        obj.cid = CidCid.constructFromObject(data['cid']);
    }
    return obj;
  }
}

/**
 * @member {module:model/CidCid} cid
 */
UtilDbCID.prototype.cid = undefined;

