--  Estuary API
--  This is the API for the Estuary application.
--
--  OpenAPI spec version: 0.0.0
--  
--
--  NOTE: This package is auto generated by the swagger code generator 2.4.29.
--  https://github.com/swagger-api/swagger-codegen.git
--  Do not edit the class manually.
with Swagger.Streams;
with Ada.Containers.Vectors;
package .Models is



   type Util_HttpError_Type is
     record
       Code : Swagger.Nullable_Integer;
       Details : Swagger.Nullable_UString;
       Reason : Swagger.Nullable_UString;
     end record;

   package Util_HttpError_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Util_HttpError_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Util_HttpError_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Util_HttpError_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Util_HttpError_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Util_HttpError_Type_Vectors.Vector);




   type Util_ContentAddResponse_Type is
     record
       Cid : Swagger.Nullable_UString;
       Estuary_Id : Swagger.Nullable_Integer;
       Providers : Swagger.Nullable_UString_Vectors.Vector;
       Retrieval_Url : Swagger.Nullable_UString;
     end record;

   package Util_ContentAddResponse_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Util_ContentAddResponse_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Util_ContentAddResponse_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Util_ContentAddResponse_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Util_ContentAddResponse_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Util_ContentAddResponse_Type_Vectors.Vector);




   type Main_getApiKeysResp_Type is
     record
       Expiry : Swagger.Nullable_UString;
       Label : Swagger.Nullable_UString;
       Token : Swagger.Nullable_UString;
       Token_Hash : Swagger.Nullable_UString;
     end record;

   package Main_getApiKeysResp_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Main_getApiKeysResp_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_getApiKeysResp_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_getApiKeysResp_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_getApiKeysResp_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_getApiKeysResp_Type_Vectors.Vector);




   type Main_deleteContentFromCollectionBody_Type is
     record
       By : Swagger.Nullable_UString;
       Value : Swagger.Nullable_UString;
     end record;

   package Main_deleteContentFromCollectionBody_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Main_deleteContentFromCollectionBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_deleteContentFromCollectionBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_deleteContentFromCollectionBody_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_deleteContentFromCollectionBody_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_deleteContentFromCollectionBody_Type_Vectors.Vector);




   type Main_ChannelIDParam_Type is
     record
       Id : Swagger.Nullable_Integer;
       Initiator : Swagger.Nullable_UString;
       Responder : Swagger.Nullable_UString;
     end record;

   package Main_ChannelIDParam_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Main_ChannelIDParam_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_ChannelIDParam_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_ChannelIDParam_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_ChannelIDParam_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_ChannelIDParam_Type_Vectors.Vector);




   type Collections_Collection_Type is
     record
       Cid : Swagger.Nullable_UString;
       Created_At : Swagger.Nullable_UString;
       Description : Swagger.Nullable_UString;
       Name : Swagger.Nullable_UString;
       User_Id : Swagger.Nullable_Integer;
       Uuid : Swagger.Nullable_UString;
     end record;

   package Collections_Collection_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Collections_Collection_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Collections_Collection_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Collections_Collection_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Collections_Collection_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Collections_Collection_Type_Vectors.Vector);




   type Main_createCollectionBody_Type is
     record
       Description : Swagger.Nullable_UString;
       Name : Swagger.Nullable_UString;
     end record;

   package Main_createCollectionBody_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Main_createCollectionBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_createCollectionBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_createCollectionBody_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_createCollectionBody_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_createCollectionBody_Type_Vectors.Vector);




   type Main_estimateDealBody_Type is
     record
       Duration_Blks : Swagger.Nullable_Integer;
       Replication : Swagger.Nullable_Integer;
       Size : Swagger.Nullable_Integer;
       Verified : Swagger.Nullable_Boolean;
     end record;

   package Main_estimateDealBody_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Main_estimateDealBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_estimateDealBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_estimateDealBody_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_estimateDealBody_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_estimateDealBody_Type_Vectors.Vector);




   type Main_importDealBody_Type is
     record
       Coluuid : Swagger.Nullable_UString;
       Deal_I_Ds : Swagger.Nullable_Integer_Vectors.Vector;
       Dir : Swagger.Nullable_UString;
       Name : Swagger.Nullable_UString;
     end record;

   package Main_importDealBody_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Main_importDealBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_importDealBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Main_importDealBody_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_importDealBody_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Main_importDealBody_Type_Vectors.Vector);




   type Util_ContentAddIpfsBody_Type is
     record
       Coluuid : Swagger.Nullable_UString;
       Dir : Swagger.Nullable_UString;
       Filename : Swagger.Nullable_UString;
       Peers : Swagger.Nullable_UString_Vectors.Vector;
       Root : Swagger.Nullable_UString;
     end record;

   package Util_ContentAddIpfsBody_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Util_ContentAddIpfsBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Util_ContentAddIpfsBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Util_ContentAddIpfsBody_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Util_ContentAddIpfsBody_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Util_ContentAddIpfsBody_Type_Vectors.Vector);




   type Util_ContentCreateBody_Type is
     record
       Coluuid : Swagger.Nullable_UString;
       Dir : Swagger.Nullable_UString;
       Location : Swagger.Nullable_UString;
       Name : Swagger.Nullable_UString;
       Root : Swagger.Nullable_UString;
       P_Type : Swagger.Nullable_Integer;
     end record;

   package Util_ContentCreateBody_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Util_ContentCreateBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Util_ContentCreateBody_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Util_ContentCreateBody_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Util_ContentCreateBody_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Util_ContentCreateBody_Type_Vectors.Vector);




   type Types_IpfsListPinStatusResponse_Type is
     record
       Count : Swagger.Nullable_Integer;
       Results : .Models.Types_IpfsPinStatusResponse_Type_Vectors.Vector;
     end record;

   package Types_IpfsListPinStatusResponse_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Types_IpfsListPinStatusResponse_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Types_IpfsListPinStatusResponse_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Types_IpfsListPinStatusResponse_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Types_IpfsListPinStatusResponse_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Types_IpfsListPinStatusResponse_Type_Vectors.Vector);




   type Types_IpfsPin_Type is
     record
       Cid : Swagger.Nullable_UString;
       Meta : Swagger.Object;
       Name : Swagger.Nullable_UString;
       Origins : Swagger.Nullable_UString_Vectors.Vector;
     end record;

   package Types_IpfsPin_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Types_IpfsPin_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Types_IpfsPin_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Types_IpfsPin_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Types_IpfsPin_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Types_IpfsPin_Type_Vectors.Vector);




   type Types_IpfsPinStatusResponse_Type is
     record
       Created : Swagger.Nullable_UString;
       Delegates : Swagger.Nullable_UString_Vectors.Vector;
       Info : Swagger.Object;
       Pin : .Models.Types_IpfsPin_Type;
       Requestid : Swagger.Nullable_UString;
       Status : Swagger.Nullable_UString;
     end record;

   package Types_IpfsPinStatusResponse_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Types_IpfsPinStatusResponse_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Types_IpfsPinStatusResponse_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Types_IpfsPinStatusResponse_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Types_IpfsPinStatusResponse_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Types_IpfsPinStatusResponse_Type_Vectors.Vector);



end .Models;
