{-
   Estuary API
   This is the API for the Estuary application.

   OpenAPI spec version: 0.0.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.Admin exposing (adminPeeringPeersDelete, adminPeeringPeersGet, adminPeeringPeersPost, adminPeeringStartPost, adminPeeringStatusGet, adminPeeringStopPost, adminSystemConfigGet, adminUsersGet)

import Data.Bool exposing (Bool, Encode.bool)
import Data.UtilHttpError exposing (UtilHttpError, utilHttpErrorDecoder)
import Data.String exposing (Decode.string, String)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "https://api.estuary.tech"


{-
   This endpoint can be used to remove a Peer from the Peering Service
-}
adminPeeringPeersDelete : Bool -> Http.Request String
adminPeeringPeersDelete model =
    { method = "DELETE"
    , url = basePath ++ "/admin/peering/peers"
    , headers = []
    , body = Http.jsonBody <| Encode.bool model
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   This endpoint can be used to list all peers on Peering Service
-}
adminPeeringPeersGet : Http.Request String
adminPeeringPeersGet =
    { method = "GET"
    , url = basePath ++ "/admin/peering/peers"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   This endpoint can be used to add a Peer from the Peering Service
-}
adminPeeringPeersPost : Http.Request String
adminPeeringPeersPost =
    { method = "POST"
    , url = basePath ++ "/admin/peering/peers"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   This endpoint can be used to start the Peering Service
-}
adminPeeringStartPost : Http.Request String
adminPeeringStartPost =
    { method = "POST"
    , url = basePath ++ "/admin/peering/start"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   This endpoint can be used to check the Peering status
-}
adminPeeringStatusGet : Http.Request String
adminPeeringStatusGet =
    { method = "GET"
    , url = basePath ++ "/admin/peering/status"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   This endpoint can be used to stop the Peering Service
-}
adminPeeringStopPost : Http.Request String
adminPeeringStopPost =
    { method = "POST"
    , url = basePath ++ "/admin/peering/stop"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   This endpoint is used to get system configs.
-}
adminSystemConfigGet : Http.Request String
adminSystemConfigGet =
    { method = "GET"
    , url = basePath ++ "/admin/system/config"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   This endpoint is used to get all users.
-}
adminUsersGet : Http.Request String
adminUsersGet =
    { method = "GET"
    , url = basePath ++ "/admin/users"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


