/* tslint:disable */
/* eslint-disable */
/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CollectionsCidType } from './collections-cid-type';
import { UtilDbCID } from './util-db-cid';
/**
 * 
 * @export
 * @interface CollectionsCollectionListResponse
 */
export interface CollectionsCollectionListResponse {
    /**
     * 
     * @type {UtilDbCID}
     * @memberof CollectionsCollectionListResponse
     */
    cid?: UtilDbCID;
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionListResponse
     */
    coluuid?: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionsCollectionListResponse
     */
    contId?: number;
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionListResponse
     */
    dir?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionListResponse
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionsCollectionListResponse
     */
    size?: number;
    /**
     * 
     * @type {CollectionsCidType}
     * @memberof CollectionsCollectionListResponse
     */
    type?: CollectionsCidType;
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionListResponse
     */
    updatedAt?: string;
}
