/* 
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using estuary-client.Api;
using estuary-client.Model;
using estuary-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace estuary-client.Test
{
    /// <summary>
    ///  Class for testing AddressAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AddressAddressTests
    {
        // TODO uncomment below to declare an instance variable for AddressAddress
        //private AddressAddress instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddressAddress
            //instance = new AddressAddress();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddressAddress
        /// </summary>
        [Test]
        public void AddressAddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddressAddress
            //Assert.IsInstanceOfType<AddressAddress> (instance, "variable 'instance' is a AddressAddress");
        }



    }

}
