/* 
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using estuary-client.Api;
using estuary-client.Model;
using estuary-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace estuary-client.Test
{
    /// <summary>
    ///  Class for testing ApiPublicNodeInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiPublicNodeInfoTests
    {
        // TODO uncomment below to declare an instance variable for ApiPublicNodeInfo
        //private ApiPublicNodeInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiPublicNodeInfo
            //instance = new ApiPublicNodeInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiPublicNodeInfo
        /// </summary>
        [Test]
        public void ApiPublicNodeInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiPublicNodeInfo
            //Assert.IsInstanceOfType<ApiPublicNodeInfo> (instance, "variable 'instance' is a ApiPublicNodeInfo");
        }


        /// <summary>
        /// Test the property 'PrimaryAddress'
        /// </summary>
        [Test]
        public void PrimaryAddressTest()
        {
            // TODO unit test for the property 'PrimaryAddress'
        }

    }

}
