//
// UtilContentAddResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UtilContentAddResponse: Codable {


    public var cid: String?

    public var estuaryId: Int?

    public var estuaryRetrievalUrl: String?

    public var providers: [String]?

    public var retrievalUrl: String?
    public init(cid: String? = nil, estuaryId: Int? = nil, estuaryRetrievalUrl: String? = nil, providers: [String]? = nil, retrievalUrl: String? = nil) { 
        self.cid = cid
        self.estuaryId = estuaryId
        self.estuaryRetrievalUrl = estuaryRetrievalUrl
        self.providers = providers
        self.retrievalUrl = retrievalUrl
    }
    public enum CodingKeys: String, CodingKey { 
        case cid
        case estuaryId
        case estuaryRetrievalUrl = "estuary_retrieval_url"
        case providers
        case retrievalUrl = "retrieval_url"
    }

}
