//
// TypesIpfsPin.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TypesIpfsPin: Codable {

    public var cid: String?
    public var meta: JSONValue?
    public var name: String?
    public var origins: [String]?

    public init(cid: String?, meta: JSONValue?, name: String?, origins: [String]?) {
        self.cid = cid
        self.meta = meta
        self.name = name
        self.origins = origins
    }


}

