//
// UtilContentAddIpfsBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UtilContentAddIpfsBody: Codable {

    public var coluuid: String?
    public var dir: String?
    public var filename: String?
    public var peers: [String]?
    public var root: String?

    public init(coluuid: String?, dir: String?, filename: String?, peers: [String]?, root: String?) {
        self.coluuid = coluuid
        self.dir = dir
        self.filename = filename
        self.peers = peers
        self.root = root
    }


}

