export * from './AdminApi';
import { AdminApi } from './AdminApi';
export * from './AutoretrieveApi';
import { AutoretrieveApi } from './AutoretrieveApi';
export * from './CollectionsApi';
import { CollectionsApi } from './CollectionsApi';
export * from './ContentApi';
import { ContentApi } from './ContentApi';
export * from './DealsApi';
import { DealsApi } from './DealsApi';
export * from './MetricsApi';
import { MetricsApi } from './MetricsApi';
export * from './MinerApi';
import { MinerApi } from './MinerApi';
export * from './NetApi';
import { NetApi } from './NetApi';
export * from './PeeringApi';
import { PeeringApi } from './PeeringApi';
export * from './PeersApi';
import { PeersApi } from './PeersApi';
export * from './PinningApi';
import { PinningApi } from './PinningApi';
export * from './PublicApi';
import { PublicApi } from './PublicApi';
export * from './UserApi';
import { UserApi } from './UserApi';
export const APIS = [AdminApi, AutoretrieveApi, CollectionsApi, ContentApi, DealsApi, MetricsApi, MinerApi, NetApi, PeeringApi, PeersApi, PinningApi, PublicApi, UserApi];
