/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_SWGDefaultApi_H_
#define _SWG_SWGDefaultApi_H_

#include "SWGHttpRequest.h"


#include <QObject>

namespace Swagger {

class SWGDefaultApi: public QObject {
    Q_OBJECT

public:
    SWGDefaultApi();
    SWGDefaultApi(QString host, QString basePath);
    ~SWGDefaultApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void dealTransferStatusPost();
    
private:
    void dealTransferStatusPostCallback (SWGHttpRequestWorker * worker);
    
signals:
    void dealTransferStatusPostSignal();
    
    void dealTransferStatusPostSignalE(QNetworkReply::NetworkError error_type, QString& error_str);
    
    void dealTransferStatusPostSignalEFull(SWGHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
