# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from estuary-client.models.base_model_ import Model
from estuary-client import util


class GithubComApplicationResearchEstuaryApiV1ClaimMsgResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hexmsg: str=None):  # noqa: E501
        """GithubComApplicationResearchEstuaryApiV1ClaimMsgResponse - a model defined in Swagger

        :param hexmsg: The hexmsg of this GithubComApplicationResearchEstuaryApiV1ClaimMsgResponse.  # noqa: E501
        :type hexmsg: str
        """
        self.swagger_types = {
            'hexmsg': str
        }

        self.attribute_map = {
            'hexmsg': 'hexmsg'
        }
        self._hexmsg = hexmsg

    @classmethod
    def from_dict(cls, dikt) -> 'GithubComApplicationResearchEstuaryApiV1ClaimMsgResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The github_com_application-research_estuary_api_v1.claimMsgResponse of this GithubComApplicationResearchEstuaryApiV1ClaimMsgResponse.  # noqa: E501
        :rtype: GithubComApplicationResearchEstuaryApiV1ClaimMsgResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hexmsg(self) -> str:
        """Gets the hexmsg of this GithubComApplicationResearchEstuaryApiV1ClaimMsgResponse.


        :return: The hexmsg of this GithubComApplicationResearchEstuaryApiV1ClaimMsgResponse.
        :rtype: str
        """
        return self._hexmsg

    @hexmsg.setter
    def hexmsg(self, hexmsg: str):
        """Sets the hexmsg of this GithubComApplicationResearchEstuaryApiV1ClaimMsgResponse.


        :param hexmsg: The hexmsg of this GithubComApplicationResearchEstuaryApiV1ClaimMsgResponse.
        :type hexmsg: str
        """

        self._hexmsg = hexmsg
