{-
   Estuary API
   This is the API for the Estuary application.

   OpenAPI spec version: 0.0.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.TypesIpfsPinStatusResponse exposing (TypesIpfsPinStatusResponse, typesIpfsPinStatusResponseDecoder, typesIpfsPinStatusResponseEncoder)

import Data.Object exposing (Object, objectDecoder, objectEncoder)
import Data.TypesIpfsPin exposing (TypesIpfsPin, typesIpfsPinDecoder, typesIpfsPinEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias TypesIpfsPinStatusResponse =
    { created : Maybe String
    , delegates : Maybe (List String)
    , info : Maybe Object
    , pin : Maybe TypesIpfsPin
    , requestid : Maybe String
    , status : Maybe String
    }


typesIpfsPinStatusResponseDecoder : Decoder TypesIpfsPinStatusResponse
typesIpfsPinStatusResponseDecoder =
    decode TypesIpfsPinStatusResponse
        |> optional "created" (Decode.nullable Decode.string) Nothing
        |> optional "delegates" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "info" (Decode.nullable objectDecoder) Nothing
        |> optional "pin" (Decode.nullable typesIpfsPinDecoder) Nothing
        |> optional "requestid" (Decode.nullable Decode.string) Nothing
        |> optional "status" (Decode.nullable Decode.string) Nothing



typesIpfsPinStatusResponseEncoder : TypesIpfsPinStatusResponse -> Encode.Value
typesIpfsPinStatusResponseEncoder model =
    Encode.object
        [ ( "created", withDefault Encode.null (map Encode.string model.created) )
        , ( "delegates", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.delegates) )
        , ( "info", withDefault Encode.null (map objectEncoder model.info) )
        , ( "pin", withDefault Encode.null (map typesIpfsPinEncoder model.pin) )
        , ( "requestid", withDefault Encode.null (map Encode.string model.requestid) )
        , ( "status", withDefault Encode.null (map Encode.string model.status) )
        ]


