//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class DefaultAPI {
    /**
     Fetch viewer details

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func viewerGet(completion: @escaping ((_ data: UtilViewerResponse?,_ error: Error?) -> Void)) {
        viewerGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Fetch viewer details
     - GET /viewer

     - API Key:
       - type: apiKey Authorization 
       - name: bearerAuth
     - examples: [{contentType=application/json, example={
  "settings" : {
    "dealDuration" : 1,
    "replication" : 2,
    "dealMakingDisabled" : true,
    "flags" : 5,
    "verified" : true,
    "fileStagingThreshold" : 5,
    "uploadEndpoints" : [ "uploadEndpoints", "uploadEndpoints" ],
    "contentAddingDisabled" : true
  },
  "address" : "address",
  "auth_expiry" : "auth_expiry",
  "perms" : 6,
  "id" : 0,
  "miners" : [ "miners", "miners" ],
  "username" : "username"
}}]

     - returns: RequestBuilder<UtilViewerResponse> 
     */
    open class func viewerGetWithRequestBuilder() -> RequestBuilder<UtilViewerResponse> {
        let path = "/viewer"
        let URLString = estuary-clientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UtilViewerResponse>.Type = estuary-clientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
