export * from './admin.service';
import { AdminService } from './admin.service';
export * from './autoretrieve.service';
import { AutoretrieveService } from './autoretrieve.service';
export * from './collections.service';
import { CollectionsService } from './collections.service';
export * from './content.service';
import { ContentService } from './content.service';
export * from './deals.service';
import { DealsService } from './deals.service';
export * from './metrics.service';
import { MetricsService } from './metrics.service';
export * from './miner.service';
import { MinerService } from './miner.service';
export * from './net.service';
import { NetService } from './net.service';
export * from './peering.service';
import { PeeringService } from './peering.service';
export * from './peers.service';
import { PeersService } from './peers.service';
export * from './pinning.service';
import { PinningService } from './pinning.service';
export * from './public.service';
import { PublicService } from './public.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AdminService, AutoretrieveService, CollectionsService, ContentService, DealsService, MetricsService, MinerService, NetService, PeeringService, PeersService, PinningService, PublicService, UserService];
