#import <Foundation/Foundation.h>
#import "SWGUtilHttpError.h"
#import "SWGApi.h"

/**
* Estuary API
* This is the API for the Estuary application.
*
* OpenAPI spec version: 0.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGNetApi: NSObject <SWGApi>

extern NSString* kSWGNetApiErrorDomain;
extern NSInteger kSWGNetApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Net Addrs
/// This endpoint is used to get net addrs
///
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error"
///
/// @return NSString*
-(NSURLSessionTask*) netAddrsGetWithCompletionHandler: 
    (void (^)(NSString* output, NSError* error)) handler;


/// Get all miners
/// This endpoint returns all miners
///
/// @param miner Filter by miner
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error"
///
/// @return NSString*
-(NSURLSessionTask*) publicMinersFailuresMinerGetWithMiner: (NSString*) miner
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Get all miners
/// This endpoint returns all miners
///
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error"
///
/// @return NSString*
-(NSURLSessionTask*) publicMinersGetWithCompletionHandler: 
    (void (^)(NSString* output, NSError* error)) handler;


/// Net Addrs
/// This endpoint is used to get net addrs
///
/// 
///  code:200 message:"OK"
///
/// @return NSArray<NSString*>*
-(NSURLSessionTask*) publicNetAddrsGetWithCompletionHandler: 
    (void (^)(NSArray<NSString*>* output, NSError* error)) handler;


/// Net Peers
/// This endpoint is used to get net peers
///
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error"
///
/// @return NSArray<NSString*>*
-(NSURLSessionTask*) publicNetPeersGetWithCompletionHandler: 
    (void (^)(NSArray<NSString*>* output, NSError* error)) handler;



@end
