/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerUtil_HttpError.h"

#include "SwaggerModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerUtil_HttpError::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Code.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("code")); WriteJsonValue(Writer, Code.GetValue());	
	}
	if (Details.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("details")); WriteJsonValue(Writer, Details.GetValue());	
	}
	if (Reason.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("reason")); WriteJsonValue(Writer, Reason.GetValue());	
	}
	Writer->WriteObjectEnd();
}

bool SwaggerUtil_HttpError::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("code"), Code);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("details"), Details);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("reason"), Reason);

	return ParseSuccess;
}
}
